name: CI - Testing

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
      - name: Ejecutar pruebas extendidas
        run: |
          python -m unittest discover -s tests/integration
